version: '3'

services:
  backend:
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    restart: always
    command: sh -c "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    env_file:
      - .env.development
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    restart: always
    command: sh -c "npm run dev"
    ports:
      - 3000:3000
    depends_on:
     - backend
    volumes:
      - /app/node_modules
      - ./frontend:/app
