version: '3'

services:
  backend:
    build: .
    command: sh -c "cd ./fastapi && uvicorn main:app --port=8000 --host=0.0.0.0"
    env_file:
      - .env.production
    ports:
      - 8000:8000
      - 3000:3000
  
  frontend:
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    command: sh -c "npm run build && node server.js"
    ports:
      - 3000:3000